version = 1

test_patterns = ["**/*_test.go"]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_path = "github.com/goreleaser/goreleaser"

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = [
    "Dockerfile",
    "Dockerfile.cgo"
  ]